apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.service.type: nodeport
    creationTimestamp: null
    labels:
      io.kompose.service: node
    name: node-svc
  spec:
    ports:
    - name: http
      port: 80
      targetPort: http
    selector:
      io.kompose.service: node
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: node-configmap
    labels:
      io.kompose.service: node
  data:
    config.js: |-
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.service.type: nodeport
    creationTimestamp: null
    name: node-deployment
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: node
      spec:
        containers:
        - image: bitnami/node-example:0.0.1
          name: node
          ports:
          - containerPort: 3000
            name: http
          livenessProbe:
            httpGet:
              path: /
              port: http
              httpHeaders:
              - name: Host
                value: app.example.com
            initialDelaySeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: http
              httpHeaders:
              - name: Host
                value: app.example.com
            initialDelaySeconds: 5
          resources: {}
          volumeMounts:
          - mountPath: /app/config.js
            name: node-config
            subPath: config.js
          - mountPath: /app/data
            name: node-data
        restartPolicy: Always
        volumes:
        - name: node-config
          configMap:
            name: node-configmap
        - name: node-data
          persistentVolumeClaim:
            claimName: node-data-pvc
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      volume.alpha.kubernetes.io/storage-class: default
    creationTimestamp: null
    labels:
      io.kompose.service: node
    name: node-data-pvc
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
  status: {}
kind: List
metadata: {}
